@startuml
start
if(whoAmI() == "CTO") then (yes)
	:Force everbody to use csv and D;
else (no)
	:Request a one table one worksheet policy;
	:Use xlsx to read spreadsheets into csv;
	:Actually use D;
endif
:Profit;
stop
@enduml
